name: Deploy Angular to VPS
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install NodeJS
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Build
  #       run: npm run build --ommit=dev
  deploy:
    # needs:
    #   - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm install -g @angular/cli
          ng build --configuration production --base-href "/proway-superdev-escola-ng/"
      - name: Deploy to gh pages
        run: |
          git config --global user.name "Francisco Lucas Janesch Lange Sens"
          git config --global user.email "francisco.lucas.sens@gmail.com"
          npx angular-cli-ghpages --dir=dist/escola-ng/browser  --no-silent
        env:
          CI: true
          GH_TOKEN: ${{ secrets.TOKEN_TO_DEPLOY }}