name: Deploy Angular to VPS
on: [workflow_dispatch]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install NodeJS
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Build
  #       run: npm run build --ommit=dev
  deploy:
    # needs:
    #   - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --ommit=dev
      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/escola-ng/browser
        env:
          CI: true
          GH_TOKEN: ${{ secrets.TOKEN_TO_DEPLOY }}